# Generated by Django 5.2.7 on 2025-11-02 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseaseprediction',
            options={'ordering': ['-prediction_date'], 'verbose_name': 'Disease Prediction', 'verbose_name_plural': 'Disease Predictions'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Patient Profile', 'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.AlterModelOptions(
            name='symptomrecord',
            options={'ordering': ['-recorded_date'], 'verbose_name': 'Symptom Record', 'verbose_name_plural': 'Symptom Records'},
        ),
        migrations.AddField(
            model_name='diseaseprediction',
            name='predicted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseaseprediction',
            name='specialist_referral',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='symptomrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_symptoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='ai_response',
            field=models.TextField(help_text='Full AI response in JSON format'),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='confidence_score',
            field=models.FloatField(help_text='Confidence percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='symptoms_analyzed',
            field=models.JSONField(help_text='List of symptoms used for prediction'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Previous medical conditions'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='symptomrecord',
            name='duration_days',
            field=models.IntegerField(help_text='How many days has this symptom persisted?'),
        ),
        migrations.AlterField(
            model_name='symptomrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='symptomrecord',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=2),
        ),
    ]
